version: "3"
services:
  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - ./app:/usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo/kudos
      - WAIT_HOSTS=mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
